appleid: georg@itzenplitz.ch
appleidhashedpassword: 254d9dd3918b5ded82724dc56d55f0c3d8995d9296063038b1c7749bc7f73df3
checkinterval: 20
databasefile: /var/lib/xapsd/database.json
delay: 111
loglevel: warn
socketpath: /var/run/dovecot/xapsd.sock
