# set the loglevel to either
# trace, debug, error, fatal, info, panic or warn
# Default: info
loglevel: info

# xapsd creates a json file to store the registration persistent on disk.
# This sets the location of the file.
databaseFile: /var/lib/xapsd/database.json

# xapsd listens on a socket for http/https requests from the dovecot plugin.
# This sets the address and port number of the listen socket.
listenAddr: '[::1]'
port: 11619

# xapsd is able to listen on a HTTPS Socket to allow HTTP/2 to be used
# SSL is enabled implicitly when certfile and keyfile exist
# !!! only use HTTPS for connection pooling with a proxy e.g. nginx or HaProxy
# !!! direct usage with the plugin is discouraged and unsupported
tlsCertfile:
tlsKeyfile:
tlsListenAddr:
tlsPort: 11620

# Notifications that are not initiated by new messages are not sent immediately for two reasons:
# 1. When you move/copy/delete messages you most likely move/copy/delete more messages within a short period of time.
# 2. You don't need your mailboxes to synchronize immediately since they are automatically synchronized when opening
#    the app
# If a new message comes and the move/copy/delete notification is still on hold it will be sent with the notification
# for the new message.
# This sets the interval to check for delayed messages.
checkInterval: 20

# Set the time how long notifications for not-new messages should be delayed until they are sent.
# Whenever checkInterval runs, it checks if "delay" <= "waiting time" and sends the notification if the expression is
# true.
delay: 30

# Name of the P12 encoded certificate and key in one file to be used to establish a connection to the APNS server
#certificateFileP12:
# Name of the PEM encoded certificate and key in one file to be used to establish a connection to the APNS server
#certificateFilePem:
#certificateFilePemKey:

# Filename of the P8 encoded key to establish a connection to the APNS server
keyFileP8:

# The following options are only required for keyFile based authentication

# APNS topic
keyFileTopic: com.apple.mail.nil
# KeyID from developer account (Certificates, Identifiers & Profiles -> Keys)
keyFileKeyId: ABCDEFGH
# TeamID from developer account (View Account -> Membership)
keyFileTeamId: ABCDEFGH
